version: '3.4'

services:
    catalogdb:
     container_name: catalogdb
     restart: always
     environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=CatalogDb
     ports:
      - "5432:5432"
     volumes:
      - postgres_catalog:/var/lib/postgressql/data/