version: '3.4'

services:
    catalogdb:
        image: postgres

    basketdb:
        image: postgres

    distributedcache:
        image: redis

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Dockerfile

    basketapi:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
            context: .
            dockerfile: Services/BasketAPI/Dockerfile

volumes:
    postgres_catalog:
    postgres_basket:


